# Generated by Django 4.2 on 2024-05-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('PRO', 'PRO'), ('BEST', 'BEST')], default='Beginner', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('question_type', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('correct_answer', models.CharField(blank=True, max_length=100)),
                ('incorrect_answer', models.CharField(blank=True, max_length=100)),
                ('answer1', models.CharField(blank=True, max_length=100)),
                ('answer2', models.CharField(blank=True, max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100)),
                ('answer4', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
