# Generated by Django 4.2 on 2024-06-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория вопроса', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('MULTIPLE  ', 'Multiple')], help_text='Тип вопроса', max_length=10)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], help_text='Сложность вопроса', max_length=100)),
                ('text', models.CharField(help_text='Текст вопроса', max_length=1000)),
                ('correct_answer', models.CharField(help_text='Правильный ответ', max_length=100)),
                ('answer1', models.CharField(help_text='1 Ответ', max_length=100)),
                ('answer2', models.CharField(help_text='2 Ответ', max_length=100)),
                ('answer3', models.CharField(help_text='3 Ответ', max_length=100)),
                ('answer4', models.CharField(help_text='4 Ответ', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Баллы')),
                ('status', models.CharField(choices=[('BEGINNER', 'Beginner'), ('AMATEUR', 'Amateur'), ('PRO', 'PRO'), ('BEST', 'BEST')], default='Beginner', help_text='Статус пользователя', max_length=8)),
                ('counter_bool', models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов правда или ложь')),
                ('counter_multiple', models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов с вариантами ответов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
