# Generated by Django 4.2 on 2024-05-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer',
            new_name='wrong_answer',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
    ]
