# Generated by Django 4.2 on 2024-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_incorrect_answer_question_wrong_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='counter_bool',
            field=models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов правда или ложь'),
        ),
        migrations.AddField(
            model_name='score',
            name='counter_multiple',
            field=models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов с вариантами ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(blank=True, help_text='1 Ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, help_text='2 Ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, help_text='3 Ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, help_text='4 Ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, help_text='Категория', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Правильный ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Сложность', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, help_text='Тип вопроса', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, help_text='Вопрос', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='wrong_answer',
            field=models.CharField(blank=True, help_text='Некорректный ответ', max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.IntegerField(default=0, help_text='Баллы'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Amateur', 'Amateur'), ('PRO', 'PRO'), ('BEST', 'BEST')], default='Beginner', help_text='Статус пользователя', max_length=8),
        ),
    ]
