# Generated by Django 4.2 on 2024-06-03 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_score_counter_bool_score_counter_multiple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Категория вопроса', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Баллы')),
                ('status', models.CharField(choices=[('BEGINNER', 'Beginner'), ('AMATEUR', 'Amateur'), ('PRO', 'PRO'), ('BEST', 'BEST')], default='Beginner', help_text='Статус пользователя', max_length=8)),
                ('counter_bool', models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов правда или ложь')),
                ('counter_multiple', models.IntegerField(default=0, help_text='Счетчик отвеченных вопросов с вариантами ответов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wrong_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], help_text='Сложность вопроса', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('BOOLEAN', 'Boolean'), ('MULTIPLE  ', 'Multiple')], help_text='Тип вопроса', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, help_text='Текст вопроса', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
    ]
